### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by potter062** [dingusagar/AsyncFaceRecognition#29]
What version of python is the project made on?

**Comment by dingusagar** [comment]
this should work on any python 3 versions. don't remember the exact version, but I think it was 3.7.
Let me know if you run into any problems.

**Comment by potter062** [comment]
Hello.
I apologize in advance for bad English. I am using google translator. I live in Ukraine.
My dataset consists of 20 people. This is 600 photos. When writing data to encodings.pickle.
Half of the data is missing. You can even say it is overwritten. You can record up to 700 kb maximum. How can I fix it?
And one more question. Can't install ISR==2.2.0

**Comment by dingusagar** [comment]
are you getting any error. could you tell me how did you conclude that the data is missing.

**Comment by potter062** [comment]
Thanks for answering. When writing to encodings.pkl . The data of the first
2 people disappear here is an example
8e+00, -3.55225876e-02, -4.81599927e-01,
        1.05992496e+00,  1.32604921e+00,  2.91034603e+00,  8.91667068e-01,
        6.91682756e-01, -1.98005125e-01, -1.25041854e+00,  2.10386246e-01,
       -2.24183992e-01,  8.54943916e-02,  1.13198686e+00,  1.51522171e+00],
      dtype=float32), array([-5.93197703e-01, -2.44849280e-01,
 6.69940889e-01, -6.84608400e-01,
       -3.05084705e-01, -3.14258426e-01, -1.72669277e-01,  1.42451620e+00,
        8.00230384e-01, -1.12180078e+00, -9.68028784e-01,  2.15252116e-03,
       -3.79678667e-01,  1.22841835e+00, -1.31649697e+00, -1.05252898e+00,
        1.25099957e+00, -1.26615298e+00,  5.45330942e-01, -2.43387818e+00,
       -9.74490285e-01, -6.95573807e-01, -1.37177482e-02, -1.02563286e+00,
       -2.30863810e-01,  6.07625663e-01,  1.85451329e+00,  7.26861835e-01,
       -1.62294328e+00,  5.87945402e-01, -2.32958865e+00, -2.98732728e-01,
       -7.92742800e-03,  7.46166348e-01,  1.02676116e-01,  4.19842601e-01,
       -4.65887308e-01,  1.93170875e-01, -6.74961090e-01,  4.17017668e-01,
       -1.05689615e-01, -6.21956289e-01,  3.58787328e-01,  8.10944855e-01,
       -2.70494282e-01, -1.00336981e+00, -3.47726971e-01, -7.04543352e-01,
        1.00188181e-01, -2.47710705e-01, -5.49921930e-01, -6.40183151e-01,
        1.18468904e+00, -1.52723634e+00,  5.35073951e-02,  2.65827626e-01,
        2.06092095e+00, -2.60119081e-01, -7.23113537e-01, -1.15217125e+00,
       -3.08004475e+00,  2.17370912e-01,  4.49331962e-02,  1.11649466e+00,
       -1.69830501e-01, -5.53841770e-01, -1.79053068e+00,  3.72677773e-01,
       -8.25434268e-01,  6.82922602e-01,  1.39229655e+00,  1.26863265e+00,
       -4.74137515e-01, -8.05336177e-01,  4.59995493e-02,  3.08684319e-01,
        2.47833341e-01,  1.60958648e-01,  6.16097331e-01, -1.16143155e+00,
        3.72342542e-02,  1.79882690e-01,  4.43943977e-01, -2.01804304e+00,
        1.30334723e+00, -8.63789767e-03,  7.27077663e-01,  4.61828828e-01,
       -1.41832507e+00,  1.19150388e+00, -3.10442597e-03, -5.80428183e-01,
       -2.90259093e-01, -4.56633657e-01,  1.52933449e-01, -3.54183465e-01,
       -2.31015891e-01,  1.26260173e+00, -3.52202803e-01,  5.73715866e-01,
        1.66010857e+00, -3.55074316e-01,  1.30641901e+00,  1.73050806e-01,
       -5.51135302e-01,  3.32333684e-01, -6.48167193e-01, -1.24197602e+00,
       -1.50674820e+00, -5.86645424e-01,  1.12291205e+00, -2.32630476e-01,
       -6.80176854e-01,  2.50989652e+00, -1.70339689e-01, -1.01551974e+00,
        1.00868392e+00,  7.58216262e-01,  2.48445749e+00,  2.87387997e-01,
        1.23971164e+00,  1.67685121e-01, -9.59461808e-01,  5.99741861e-02,
       -4.28002715e-01, -1.36634782e-02,  1.07431352e+00,  1.49950075e+00],
      dtype=float32), array([-1.0132158 , -0.36180976,  1.2255532 ,
-0.93182427,  0.19130202,
       -0.793655  , -0.27712497,  1.046442  ,  0.1549536 , -1.5128535 ,
       -0.58640724, -0.00877453, -0.5500633 ,  1.3409097 , -1.204546  ,
       -0.15160069,  1.1770606 , -0.646917  ,  1.0244946 , -2.4642777 ,
       -0.955511  , -0.311618  ,  0.20754856, -1.8125849 , -0.17729479,
        0.68578094,  1.8838041 ,  0.85420114, -1.7308745 ,  0.5185362 ,
       -2.4853997 , -0.14833282, -0.15057462,  1.1242064 ,  0.07758489,
        0.91015065, -0.48657146, -0.09442873, -0.5752774 ,  0.5834662 ,
       -0.12472545, -0.7695678 ,  0.45511088,  1.569769  , -0.49972585,
       -0.76765984, -0.7805185 , -1.2791882 , -0.13335785, -0.14584184,
       -1.0171305 , -0.48499823,  1.028613  , -0.7120265 ,  0.79869384,
       -0.6179025 ,  1.6115575 ,  0.3510411 , -0.7324181 , -1.2227182 ,
       -2.5276003 , -0.36331844,  0.32789412,  1.1709535 , -0.2185117 ,
       -0.83058006, -1.9500022 ,  0.10180141, -1.1904817 ,  0.6137136 ,
        0.53208286,  1.3876935 , -0.6074332 , -0.6839715 , -0.15569836,
        0.90730333, -0.07092063,  0.6887939 ,  1.4342077 , -1.014649  ,
        0.16471034,  0.80718756, -0.03904774, -1.686769  ,  0.79711473,
       -0.37295058,  0.23561394,  0.4659875 , -2.029835  ,  0.9454246 ,
        0.4121217 , -0.1863903 , -0.5014393 , -1.233092  ,  0.1125263 ,
       -0.845238  , -0.76882607,  0.90486836,  0.10249799,  0.10284805,
        1.2776397 , -0.45868316,  0.6192282 ,  0.38700616, -0.02487881,
        0.1338067 , -0.74911207, -1.0520244 , -2.0814996 , -1.4532849 ,
        1.2863524 , -0.5432614 ,  0.25881267,  2.579467  ,  0.20122887,
       -0.9338939 ,  1.463858  ,  0.5796071 ,  2.7184808 ,  1.0458077 ,
        0.62293476,  0.2173001 , -0.8095709 , -0.09898236, -0.1376905 ,
       -0.101684  ,  1.2480782 ,  1.6106695 ], dtype=float32),
array([-0.11940707, -0.33811328,  1.2087729 , -0.9396469 , -1.3240453 ,
        0.5892271 , -0.06666989,  0.5531702 ,  0.39315024, -1.4721326 ,
       -0.867742  ,  0.46879956, -0.03249725,  1.2081184 , -1.608266  ,
       -0.56826526,  0.38639134, -1.4040235 , -0.05907214, -0.82422954,
       -0.42820412, -0.8380793 , -0.15577713, -0.8727363 ,  1.0348676 ,
       -0.11597148,  1.8264841 ,  0.72093153, -1.554932  ,  0.07317662,
       -2.058619  ,  0.12785262, -0.41487056,  1.624397  , -0.6487343 ,
        0.6064692 , -1.2053827 , -0.65834093, -0.43007034,  1.3267012 ,
        0.28077206, -0.16563804, -0.36641482,  1.0051935 , -0.15212229,
       -1.273517  , -1.2277166 ,  0.27152508,  0.37097806, -0.876541  ,
       -1.5500797 , -0.7034156 ,  1.3592205 , -1.23786   ,  0.61470824,
       -0.52352035,  2.5686324 ,  0.42078945, -1.7720706 , -1.2880093 ,
       -2.4949744 ,  0.6305157 , -0.63290715,  1.9101835 , -0.08085342,
        0.15991834, -0.9351053 ,  0.04878691, -0.2260567 , -0.05259006,
        1.2355744 ,  1.2653611 , -0.4164909 ,  0.12601155,  0.6529282 ,
       -0.23485997, -0.33202454,  0.71245736,  1.3856884 ,  0.242678  ,
        0.52625984, -0.4289212 ,  0.6036429 , -2.013526  ,  2.4218986 ,
        0.55751663,  0.23984027,  0.6735482 , -1.8953731 ,  1.3701571 ,
        0.93394876, -0.56127924, -0.13580787, -0.19419661,  0.71935874,
        1.1102973 , -0.7564801 ,  1.1023118 , -0.71397704,  0.10959695,
        1.1440407 , -0.15595536,  0.20614475,  0.13488649, -1.3849567 ,
       -0.33087778, -0.55336004, -1.4093138 , -1.8342322 , -1.6034243 ,
        0.55108166,  0.3008402 ,  0.19354014,  0.9101249 , -0.22756314,
        0.51455355,  0.82408094,  1.352174  ,  2.5797899 ,  0.4911383 ,
        1.6520694 , -0.21240117, -0.01092896, -1.4146632 ,  0.19578232,
       -0.69900423,  1.0098188 ,  1.8085041 ], dtype=float32),
array([-0.4019244 , -0.22492737,  1.0405725 , -0.85176635, -0.62851024,
       -0.06756275, -0.35522547,  0.8867052 ,  0.92883337, -1.4357976 ,
       -0.5321762 , -0.25522286, -0.30163264,  1.3142087 , -1.5443392 ,
       -1.2056555 ,  1.2759063 , -1.3543676 , -0.14013958, -2.5416014 ,
       -1.2040377 , -1.4653587 , -0.26381192, -0.31514993,  0.19363043,
        0.7548582 ,  2.2527797 ,  0.85364413, -1.5328969 ,  0.6527351 ,
       -2.035131  ,  0.0104444 , -0.11091251,  0.8130467 ,  0.04449353,
        0.79875433, -0.8971542 , -0.1537149 , -0.76122785,  1.3351122 ,
        0.21390112, -1.0165498 ,  0.13591462,  1.0735629 , -0.33481637,
       -1.5753052 , -0.24000798, -0.56160057,  0.2864526 , -1.2836859 ,
       -0.5062188 , -1.2408966 ,  1.2788824 , -1.3537254 ,  0.35950562,
        0.40589485,  2.6384184 , -0.58141446, -1.137591  , -0.99071676,
       -3.049458  ,  0.34016782,  0.16968869,  1.3504585 , -0.29373524,
       -0.03399567, -1.8454291 ,  0.58407485, -0.36397275,  0.85136247,
        1.3694377 ,  1.4559845 , -0.04001276, -0.65432894,  0.428677  ,
        0.3379768 ,  0.2821174 ,  0.6173912 ,  0.8285009 , -0.9374638 ,
        0.1907148 , -0.27653882,  0.2920445 , -2.240071  ,  1.906796  ,
        0.49354133,  0.46647152,  0.18353517, -1.0971624 ,  1.3666843 ,
        0.6765113 , -0.74877   , -0.2911105 , -0.8011828 ,  0.2867362 ,
        0.9559758 , -0.43960032,  1.2449304 , -0.73098814,  0.11811244,
        1.360424  ,  0.22946206,  1.4343873 , -0.2700839 , -0.35047144,
        0.02404444, -0.90376115, -1.2539499 , -1.3365563 , -1.0591111 ,

and at the end of the file looks like this

dtype=float32), array([ 0.7018205 , -0.3919468 ,  0.08050837, -1.2006559 ,
 1.355657  ,
        0.04792313,  0.34780088, -0.60695624, -1.8261516 ,  0.66278243,
       -0.47091714,  0.40752548,  0.99274   , -1.2499919 , -0.56883705,
       -0.34320813, -0.48021814, -0.14300832,  1.9145831 ,  1.2759411 ,
        0.40249273,  1.0679086 , -1.3818071 ,  1.2378441 ,  0.46280497,
       -0.2410461 , -0.63547456,  0.44597468, -0.12832023, -0.35987976,
        1.7895048 ,  0.19176927, -0.04446073, -0.00435889, -1.9078285 ,
       -1.043589  ,  1.7809669 , -0.81324476,  0.28552777,  0.19083458,
       -0.34182414,  0.34478635,  0.23472375,  1.3350343 , -0.308816  ,
        0.1826087 , -1.2063439 ,  1.2658052 ,  0.0268992 , -0.5657798 ,
       -1.551849  ,  0.36377698, -1.5486187 ,  1.0036651 , -0.5088408 ,
       -0.61199653,  0.07302341, -0.64260423, -0.24974108,  0.8573929 ,
        1.1569446 ,  0.66503704, -1.3616439 ,  0.6705988 , -1.3393793 ,
        1.8723596 ,  0.40525493, -0.66953844, -0.79747945,  0.7521814 ,
       -0.09388006, -0.5676439 ,  1.2352537 , -0.0477856 ,  1.701699  ,
        0.2583663 ,  0.38662705,  1.4237623 ,  0.15693364,  2.871024  ,
       -1.7303656 ,  1.258052  , -0.8856478 , -0.47621465,  0.12775382,
        1.6096131 , -1.0037658 , -0.17423624,  1.1250086 ,  0.50825554,
        1.0633918 ,  0.0369445 , -1.4206749 , -1.2686751 ,  2.9490352 ,
       -0.97424823,  0.04904006, -1.4855934 , -0.47141793, -1.2284883 ,
        1.0025253 , -0.26513395, -0.2395707 , -0.74560374, -0.5580364 ,
       -0.61161137,  1.8131689 , -0.98212326,  1.5158426 , -1.0397644 ,
       -1.4319592 , -1.6964734 ,  0.10215981, -0.34090078, -0.1078623 ,
        0.3575187 , -0.94586456,  0.78174824, -0.4009974 ,  0.9041139 ,
        0.05249559,  1.032325  ,  0.2145375 , -0.8770265 ,  0.8147432 ,
       -1.3598316 ,  1.1617779 ,  0.2136006 ], dtype=float32)]}

Process finished with exit code 0

no out of memory errors

вт, 9 мая 2023 г. в 13:26, Dingu Sagar ***@***.***>:

**Comment by dingusagar** [comment]
can you send me the encodings.pkl, I can take a look at it and see what is wrong. 
if you want, you can email it to dingusagar@gmail.com

**Comment by potter062** [comment]
I wrote you an email   ***@***.***

ср, 17 мая 2023 г. в 07:46, Dingu Sagar ***@***.***>:

**Comment by dingusagar** [comment]
Hi, 
Got the emal but I couldn't check yet since was little busy this week.
I will check this soon by this weekend and get back to you.

**Comment by potter062** [comment]
Привет
Я хотел бы извиниться перед вами за причиненные неудобства. Проблема в том,
что у меня нет знаний. Когда я проверил отладку кода, я понял, что ошибался

*Если у вас есть подсказка, как отправить сообщение в телеграм при
определении человека, то поделитесь, пожалуйста. Нет способа сделать это.*
*Очень хотелось бы увидеть урок по реализации распознавания лиц с телеграмм
оповещением на ютубе.*



чт, 25 мая 2023 г. в 04:59, Dingu Sagar ***@***.***>:
