### ISSUE TITLE
encodings.pickle

### ISSUE THREAD

**Issue by potter062** [dingusagar/AsyncFaceRecognition#30]
Hello.
I apologize in advance for bad English. I am using google translator. I live in Ukraine.
My dataset consists of 20 people. This is 600 photos. When writing data to encodings.pickle.
Half of the data is missing. You can even say it is overwritten. You can record up to 700 kb maximum. How can I fix it?

**Comment by potter062** [comment]
Question removed. When checking through debug, it works.

**Comment by dingusagar** [comment]
okay, great. I was about to debug the pickle file. 
Anyways, let me know if you face any other issues. Happy to help.
