### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by noorfaleh** [dingusagar/AsyncFaceRecognition#4]
[errors1.docx](https://github.com/dingusagar/AsyncFaceRecognition/files/5876315/errors1.docx)
[errors.docx](https://github.com/dingusagar/AsyncFaceRecognition/files/5876294/errors.docx)

**Comment by dingusagar** [comment]
for some reason pip3 is trying to install multiple versions of ISR package and the dependencies are conflicting. Not sure why this is happening. 
Can you try installing a specific version of ISR. 
you can try this command to install a specific version. 
`pip3 install ISR==2.2.0`

**Comment by noorfaleh** [comment]
Hello ,
Yes I do 


What’s the wrong?
яєgαя∂ѕ
ησσя
